dynamic_token_manager.dynamic_token_instance.*.plugin_config.dynamic_text_token:
  type: mapping
  label: 'Dynamic Text Token config'
  mapping:
    values:
      type: sequence
      label: 'Values'
      sequence:
        type: string
    seed:
      type: integer
      label: 'Seed'
